name: Build and publish Docker image

on:
  push:
    tags:
    - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out repo
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: fitiotlab/iot-lab-websocket
          tags: type=pep440,pattern={{version}}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
